# Generated by Django 5.0.6 on 2024-05-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='urls',
            new_name='urlDB',
        ),
    ]
